// Skins — the theme catalog and its validation.
//
// A theme is a full site skin, not an accent swatch: the whole CSS variable
// palette plus up to four image layers (page backdrop, header band, corner
// cutout, empty-state watermark). The client applies it by writing the
// variables and injecting the layers; nothing here renders anything.
//
// Two layers, the same shape the schedule corrections use:
//   1. site/data/themes.json — the committed seed, generated by
//      scripts/build-themes.mjs from each show's own art and dominant colour.
//      Ships inside the function bundle via `included_files` in netlify.toml.
//   2. the "site-themes" Blobs store — what /admin writes. Merged on top, so a
//      new theme for an event costs no deploy (~15 of 300 monthly credits).
//
// Image URLs are external by design — the seed points at AniList's CDN, which
// the app already preconnects to and loads every cover from. That means a theme
// is pure JSON: no binaries in the repo, no upload endpoint, no per-theme
// deploy. The cost is that a theme is only as available as its host, which is
// why validateThemes() insists on https and why build-themes.mjs --check exists.

export const THEMES_VERSION = 1;
export const THEME_STORE = "site-themes";

// Every colour the app themes. A skin must set all of them: a partial palette
// leaves half the UI on the stock purple, which looks like a bug rather than a
// theme. The generator always emits the full set.
export const THEME_COLORS = [
  "bg", "bg2", "bg3", "line", "txt", "muted",
  "accent", "accent2", "premiere", "today", "good", "now", "finale",
];
// Photographic layers (external art) and drawn layers (generated SVG). The
// split matters: a photo has to come from a host, a pattern is cheaper and more
// reliable generated than sourced, and only the drawn ones accept data: URIs.
export const THEME_LAYERS = ["backdrop", "header", "cutout", "watermark", "pattern", "ornament"];
const DRAWN_LAYERS = new Set(["pattern", "ornament"]);
const CORNERS = ["bottom-right", "bottom-left", "top-right", "top-left"];

const HEX = /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i;
// These URLs end up inside a CSS url("…"). Quotes, backslashes, parens and
// whitespace are the characters that close it and start a new declaration, so
// they are rejected here as well as in the browser — the client has the same
// check, and neither should be the only one doing it.
const SAFE_URL = /^https:\/\/[^"'\\\s()]+$/i;
// Inline SVG for the drawn layers — textures and ornaments that are generated
// from the palette rather than fetched. No host to go down, no 404 six months
// from now, and a pattern that is actually made of the theme's own colours.
//
// Safe as a CSS background specifically: an SVG referenced by background-image
// renders in the browser's secure static mode, where script, foreignObject and
// external references are all inert. The character class below is the same
// no-quotes/no-parens/no-whitespace rule the https branch uses, so it can't
// break out of the url() either.
const SAFE_DATA = /^data:image\/svg\+xml,[A-Za-z0-9%._~!$&*+,;:@/=-]+$/;
const safeLayerUrl = (name, url) =>
  DRAWN_LAYERS.has(name) ? (SAFE_URL.test(url) || SAFE_DATA.test(url)) : SAFE_URL.test(url);

// Shape and typography are what make a skin read as a different product rather
// than a re-tinted one. Bounded so a theme can restyle the site but never make
// it unusable — a 40px radius on a calendar cell is a choice, a 400px one is a
// broken layout.
const SHAPE_LIMITS = { radius: [0, 28], chipRadius: [0, 30], border: [1, 3], cardBlur: [0, 24] };
const EFFECT_KEYS = ["vignette", "grain", "scanlines", "glowStrength"];

export async function loadThemeSeed(siteUrl) {
  const { readFile } = await import("node:fs/promises");
  const { join } = await import("node:path");
  const roots = [process.cwd(), process.env.LAMBDA_TASK_ROOT, "/var/task"].filter(Boolean);
  for (const root of roots) {
    try { return JSON.parse(await readFile(join(root, "site", "data", "themes.json"), "utf8")); }
    catch { /* try the next root */ }
  }
  if (siteUrl) {
    try {
      const r = await fetch(`${siteUrl}/data/themes.json`);
      if (r.ok) return await r.json();
    } catch { /* fall through */ }
  }
  console.warn("themes: seed not found on disk or over HTTP — live store only");
  return null;
}

// Whole themes replace whole themes. Deep-merging a palette would let a live
// edit leave a theme half-old and half-new, and "why is one pill still green"
// is not a debugging session anyone should have.
export function mergeThemes(seed, live) {
  const out = { version: THEMES_VERSION, themes: { ...((seed && seed.themes) || {}) } };
  for (const [id, rec] of Object.entries((live && live.themes) || {})) out.themes[id] = rec;
  out.updatedAt = (live && live.updatedAt) || (seed && seed.generatedAt) || null;
  return out;
}

function badLayer(name, layer) {
  if (layer == null) return null;                       // absent = that layer is off
  if (typeof layer !== "object") return `${name} is not an object`;
  if (layer.url != null) {
    if (typeof layer.url !== "string") return `${name}.url is not a string`;
    // Empty is how a layer is switched off while keeping its settings around.
    if (layer.url && !safeLayerUrl(name, layer.url)) {
      return DRAWN_LAYERS.has(name)
        ? `${name}.url must be an https:// URL or a data:image/svg+xml URI, with no quotes, spaces or parentheses`
        : `${name}.url must be an https:// URL with no quotes, spaces or parentheses`;
    }
    // Generated SVG is inline, so it needs far more headroom than a link.
    const max = DRAWN_LAYERS.has(name) ? 20000 : 500;
    if (layer.url.length > max) return `${name}.url is too long (max ${max})`;
  }
  for (const k of ["opacity", "blur", "width", "size", "offsetX", "offsetY", "fade"]) {
    if (layer[k] != null && !Number.isFinite(layer[k])) return `${name}.${k} is not a number`;
  }
  if (layer.opacity != null && (layer.opacity < 0 || layer.opacity > 1)) return `${name}.opacity must be between 0 and 1`;
  if (layer.fade != null && (layer.fade < 0 || layer.fade > 1)) return `${name}.fade must be between 0 and 1`;
  if ((name === "cutout" || name === "ornament") && layer.corner != null && !CORNERS.includes(layer.corner)) {
    return `${name}.corner must be one of ${CORNERS.join(", ")}`;
  }
  if (layer.position != null && (typeof layer.position !== "string" || layer.position.length > 40)) {
    return `${name}.position is not a short CSS position string`;
  }
  return null;
}

// A web font is the single biggest lever a skin has on how the site *feels*,
// so it is part of the theme — but only for display text. Body copy and the
// calendar keep the system stack: a decorative face at 12px across a grid of
// air times is a skin that made the product worse.
function badFont(font) {
  if (font == null) return null;
  if (typeof font !== "object") return "font is not an object";
  if (font.family != null && (typeof font.family !== "string" || font.family.length > 120)) return "font.family is not a short CSS font stack";
  // Reject anything that could close the declaration or smuggle another one in.
  if (font.family && /[;{}<>]/.test(font.family)) return "font.family contains invalid characters";
  if (font.css != null) {
    if (typeof font.css !== "string" || !/^https:\/\/fonts\.googleapis\.com\//.test(font.css)) {
      return "font.css must be a https://fonts.googleapis.com/ stylesheet URL";
    }
    if (/["'\\<>]/.test(font.css)) return "font.css contains invalid characters";
  }
  if (font.scale != null && (!Number.isFinite(font.scale) || font.scale < 0.8 || font.scale > 1.6)) {
    return "font.scale must be between 0.8 and 1.6";
  }
  return null;
}

function badShape(shape) {
  if (shape == null) return null;
  if (typeof shape !== "object") return "shape is not an object";
  for (const [k, [lo, hi]] of Object.entries(SHAPE_LIMITS)) {
    const v = shape[k];
    if (v == null) continue;
    if (!Number.isFinite(v)) return `shape.${k} is not a number`;
    if (v < lo || v > hi) return `shape.${k} must be between ${lo} and ${hi}`;
  }
  return null;
}

function badEffects(fx) {
  if (fx == null) return null;
  if (typeof fx !== "object") return "effects is not an object";
  for (const k of EFFECT_KEYS) {
    const v = fx[k];
    if (v == null) continue;
    if (!Number.isFinite(v) || v < 0 || v > 1) return `effects.${k} must be between 0 and 1`;
  }
  return null;
}

// Reject a malformed document before it is written. The live store is read by
// every visitor, so a bad blob here is a bad blob for everyone at once —
// exactly the reasoning behind validateOverrides().
export function validateThemes(doc) {
  if (!doc || typeof doc !== "object") return "not an object";
  if (!doc.themes || typeof doc.themes !== "object") return "missing themes{}";
  const ids = Object.keys(doc.themes);
  if (ids.length > 200) return "too many themes (max 200)";
  for (const id of ids) {
    if (!/^[a-z0-9][a-z0-9-]{0,39}$/.test(id)) return `theme key "${id}" must be lowercase letters, digits and dashes`;
    const t = doc.themes[id];
    if (!t || typeof t !== "object") return `theme ${id} is not an object`;
    if (t.name != null && typeof t.name !== "string") return `theme ${id}.name is not a string`;
    if (t.mode != null && !["dark", "light"].includes(t.mode)) return `theme ${id}.mode must be "dark" or "light"`;
    if (!t.colors || typeof t.colors !== "object") return `theme ${id} has no colors{}`;
    for (const key of THEME_COLORS) {
      const v = t.colors[key];
      if (v == null) return `theme ${id} is missing colors.${key}`;
      if (!HEX.test(v)) return `theme ${id}.colors.${key} is not a hex colour`;
    }
    if (t.glow != null && !HEX.test(t.glow)) return `theme ${id}.glow is not a hex colour`;
    for (const layer of THEME_LAYERS) {
      const problem = badLayer(layer, t[layer]);
      if (problem) return `theme ${id}: ${problem}`;
    }
    for (const [label, check, value] of [["font", badFont, t.font], ["shape", badShape, t.shape], ["effects", badEffects, t.effects]]) {
      const problem = check(value);
      if (problem) return `theme ${id}: ${problem}`;
      void label;
    }
  }
  return null;
}

// What the browser needs, and nothing it doesn't. Also the choke point that
// guarantees a client can trust every colour it is handed: anything that isn't
// a hex colour never reaches the CSS variable it would be written into.
export function publicTheme(id, t) {
  const colors = {};
  for (const key of THEME_COLORS) if (HEX.test(t.colors[key] || "")) colors[key] = t.colors[key];
  const out = {
    id,
    name: t.name || id,
    series: t.series || null,
    mediaId: t.mediaId || null,
    mode: t.mode === "light" ? "light" : "dark",
    colors,
    glow: HEX.test(t.glow || "") ? t.glow : colors.accent || null,
  };
  const clamp = (v, lo, hi, dflt) => (Number.isFinite(v) ? Math.min(hi, Math.max(lo, v)) : dflt);

  for (const layer of THEME_LAYERS) {
    const l = t[layer];
    if (!l || !l.url || !safeLayerUrl(layer, l.url)) continue;
    out[layer] = {
      url: l.url,
      opacity: clamp(l.opacity, 0, 1, 0.3),
      blur: clamp(l.blur, 0, 20, 0),
      position: typeof l.position === "string" ? l.position.slice(0, 40) : "center",
    };
    if (layer === "cutout" || layer === "ornament") {
      const o = out[layer];
      o.corner = CORNERS.includes(l.corner) ? l.corner : "bottom-right";
      o.width = clamp(l.width, 80, 900, layer === "cutout" ? 340 : 240);
      o.offsetX = clamp(l.offsetX, -400, 400, 0);
      o.offsetY = clamp(l.offsetY, -400, 400, 0);
      o.flip = !!l.flip;
      // How hard the edges dissolve into the page. This is what turns a
      // rectangle of poster art into something that belongs in the layout —
      // without it a cutout reads as a screenshot pasted into the corner.
      o.fade = clamp(l.fade, 0, 1, layer === "cutout" ? 0.55 : 0);
    }
    if (layer === "pattern") out.pattern.size = clamp(l.size, 8, 600, 160);
  }

  if (t.font && typeof t.font === "object" && !badFont(t.font)) {
    out.font = {
      family: t.font.family || null,
      css: t.font.css || null,
      scale: clamp(t.font.scale, 0.8, 1.6, 1),
    };
  }
  const shape = t.shape && typeof t.shape === "object" && !badShape(t.shape) ? t.shape : {};
  out.shape = {
    radius: clamp(shape.radius, ...SHAPE_LIMITS.radius, 12),
    chipRadius: clamp(shape.chipRadius, ...SHAPE_LIMITS.chipRadius, 20),
    border: clamp(shape.border, ...SHAPE_LIMITS.border, 1),
    cardBlur: clamp(shape.cardBlur, ...SHAPE_LIMITS.cardBlur, 10),
  };
  const fx = t.effects && typeof t.effects === "object" && !badEffects(t.effects) ? t.effects : {};
  out.effects = {
    vignette: clamp(fx.vignette, 0, 1, 0),
    grain: clamp(fx.grain, 0, 1, 0),
    scanlines: clamp(fx.scanlines, 0, 1, 0),
    glowStrength: clamp(fx.glowStrength, 0, 1, 0.4),
  };
  return out;
}
